name: Build macOS Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to upload to'
        required: true
        default: 'v0.1.1'

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64-apple-darwin, aarch64-apple-darwin]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Build release binary
        run: |
          cargo build --release --target ${{ matrix.target }}
      
      - name: Create tarball
        run: |
          mkdir -p dist
          tar czf dist/cortex-${{ github.event.inputs.release_tag }}-${{ matrix.target }}.tar.gz \
            -C target/${{ matrix.target }}/release cortex
      
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.inputs.release_tag }} \
            dist/cortex-${{ github.event.inputs.release_tag }}-${{ matrix.target }}.tar.gz \
            --clobber