name: Publish to PPA

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.1.0'
      distribution:
        description: 'Ubuntu distribution'
        required: true
        type: choice
        options:
          - focal
          - jammy
          - noble

jobs:
  publish:
    name: Publish to Ubuntu PPA
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            devscripts debhelper dput gnupg lintian \
            build-essential cargo rustc pkg-config libssl-dev
      
      - name: Setup GPG
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          mkdir -p ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
      
      - name: Prepare build
        env:
          VERSION: ${{ github.event.inputs.version }}
          DIST: ${{ github.event.inputs.distribution }}
        run: |
          # Set version
          if [ "$DIST" = "focal" ]; then
            FULL_VERSION="${VERSION}-1ubuntu1"
          else
            FULL_VERSION="${VERSION}-1ubuntu1~${DIST}1"
          fi
          echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
          
          # Create build directory
          BUILD_DIR=~/ppa-build
          mkdir -p $BUILD_DIR
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
          
          # Prepare source
          WORK_DIR="$BUILD_DIR/cortex-${VERSION}"
          rm -rf "$WORK_DIR"
          mkdir -p "$WORK_DIR"
          
          # Copy source
          tar --exclude='.git' --exclude='target' --exclude='*.deb' -cf - . | \
            (cd "$WORK_DIR" && tar -xf -)
          
          # Create orig tarball
          cd "$BUILD_DIR"
          tar czf "cortex_${VERSION}.orig.tar.gz" "cortex-${VERSION}"
          
          echo "WORK_DIR=$WORK_DIR" >> $GITHUB_ENV
      
      - name: Create debian files
        working-directory: ${{ env.WORK_DIR }}
        env:
          VERSION: ${{ github.event.inputs.version }}
          DIST: ${{ github.event.inputs.distribution }}
          DEBEMAIL: ${{ secrets.DEBEMAIL }}
          DEBFULLNAME: ${{ secrets.DEBFULLNAME }}
        run: |
          mkdir -p debian/source
          echo "3.0 (quilt)" > debian/source/format
          echo "12" > debian/compat
          
          # Create control file
          cat > debian/control << 'END'
          Source: cortex
          Section: utils
          Priority: optional
          Maintainer: Ashish Tyagi <ashishtyagi10@gmail.com>
          Build-Depends: debhelper-compat (= 12),
                         cargo,
                         rustc (>= 1.70),
                         pkg-config
          Standards-Version: 4.5.1
          Homepage: https://github.com/trinverse/cortex
          
          Package: cortex
          Architecture: any
          Depends: ${shlibs:Depends}, ${misc:Depends}
          Description: Modern terminal file manager
           Cortex is a powerful terminal file manager written in Rust.
           Features dual-pane interface, vim-style navigation, and plugin support.
          END
          
          # Fix indentation in control file
          sed -i 's/^          //' debian/control
          
          # Create rules file
          cat > debian/rules << 'END'
          #!/usr/bin/make -f
          
          export DH_VERBOSE = 1
          export CARGO_HOME = $(CURDIR)/debian/cargo
          
          %:
          	dh $@
          
          override_dh_auto_build:
          	cargo build --release --locked
          
          override_dh_auto_install:
          	install -Dm755 target/release/cortex debian/cortex/usr/bin/cortex
          
          override_dh_auto_test:
          	# Skip tests
          
          override_dh_auto_clean:
          	cargo clean
          	dh_auto_clean
          END
          
          # Fix indentation in rules file
          sed -i 's/^          //' debian/rules
          chmod +x debian/rules
          
          # Create changelog
          cat > debian/changelog << END
          cortex (${FULL_VERSION}) ${DIST}; urgency=medium
          
            * Release version ${VERSION} for Ubuntu ${DIST}
          
           -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)
          END
          
          # Create copyright
          cat > debian/copyright << 'END'
          Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
          Upstream-Name: cortex
          Source: https://github.com/trinverse/cortex
          
          Files: *
          Copyright: 2024-2025 Trinverse
          License: MIT
           Permission is hereby granted, free of charge, to any person obtaining a
           copy of this software and associated documentation files (the "Software"),
           to deal in the Software without restriction.
          END
          
          # Fix indentation
          sed -i 's/^          //' debian/copyright
      
      - name: Build source package
        working-directory: ${{ env.BUILD_DIR }}
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          cd cortex-*
          
          # Build with GPG signing
          echo "$GPG_PASSPHRASE" | debuild -S -sa -d \
            -k"$GPG_KEY_ID" \
            -p"gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback"
      
      - name: Upload to PPA
        working-directory: ${{ env.BUILD_DIR }}
        env:
          LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
        run: |
          # Configure dput
          cat > ~/.dput.cf << END
          [cortex-ppa]
          fqdn = ppa.launchpad.net
          method = ftp
          incoming = ~${LAUNCHPAD_USERNAME}/ubuntu/cortex
          login = anonymous
          allow_unsigned_uploads = 0
          END
          
          # Upload
          dput cortex-ppa *.changes
      
      - name: Summary
        run: |
          echo "## ✅ PPA Upload Complete!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- Distribution: ${{ github.event.inputs.distribution }}" >> $GITHUB_STEP_SUMMARY
          echo "- PPA: ppa:${{ secrets.LAUNCHPAD_USERNAME }}/cortex" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Check build status: https://launchpad.net/~${{ secrets.LAUNCHPAD_USERNAME }}/+archive/ubuntu/cortex" >> $GITHUB_STEP_SUMMARY