name: Publish to PPA (Simple)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.1.0'

jobs:
  publish:
    name: Publish to Ubuntu PPA
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts debhelper dput gnupg lintian \
            build-essential cargo rustc pkg-config libssl-dev
      
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye
      
      - name: Build packages
        env:
          VERSION: ${{ github.event.inputs.version }}
          DEBEMAIL: ${{ secrets.DEBEMAIL }}
          DEBFULLNAME: ${{ secrets.DEBFULLNAME }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          LAUNCHPAD_USERNAME: ${{ secrets.LAUNCHPAD_USERNAME }}
        run: |
          chmod +x packaging/debian/build-ppa-package.sh
          
          # Create answers file for non-interactive mode
          cat > /tmp/ppa-answers << ANSWERS
          ${LAUNCHPAD_USERNAME}
          ${DEBEMAIL}
          ${GPG_KEY_ID}
          4
          y
          ANSWERS
          
          # Run build script with answers
          packaging/debian/build-ppa-package.sh < /tmp/ppa-answers
      
      - name: Summary
        run: |
          echo "## PPA Upload Complete!" >> $GITHUB_STEP_SUMMARY
          echo "Check build status at: https://launchpad.net/~${{ secrets.LAUNCHPAD_USERNAME }}/+archive/ubuntu/cortex" >> $GITHUB_STEP_SUMMARY